name = (input("Enter your Name: " ))
age = (input("Enter your Age: " ))
occupation = (input("Enter your Occupation: "))
email_address = (input("Enter your Email Address: "))
number = (input("Enter your Phone Number: "))
fathers_name = (input("Enter your Fathers Name: "))
fathers_number = (input("Enter your Fathers Number: "))
mothers_name = (input("Input your Mothers Name: "))
mothers_number = (input ("Input your Mothers Number: "))
address = (input("Input your Address: "))

print(name)
print(age)
print(occupation)
print (email_address)
print (number)
print (fathers_name)
print (fathers_number)
print (mothers_name)
print (mothers_number)
print (address)